version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports: 
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2